config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'time_regs#index'

  resources :project_reports do
    patch :update_group
    collection do
      get 'update_projects_selection'
      get 'update_members_checkboxes'
      get 'update_tasks_checkboxes'
      post 'export'
    end
  end

  resources :user_reports do
    patch :update_group
    collection do
      post 'export'
      get 'update_projects_checkboxes'
      get 'update_tasks_checkboxes'
    end
  end

  resources :clients

  resources :tasks

  match 'projects/import' => 'projects#import', :via => :post
  resources :time_regs do
    patch :toggle_active
    collection do
      get 'export'
      post 'import'
      get 'update_tasks_select'
      get 'new_modal', to: 'time_regs#new', as: :new_modal
    end
  end

  resources :projects do
    resources :memberships
    resources :assigned_tasks
    get 'export', to: 'projects#export', as: 'export_project_time_reg'
  end
end

app/models/time_reg.rb
class TimeReg < ApplicationRecord
  validates :notes, format: { without: /\r|\n/, message: 'Line breaks are not allowed' }

  belongs_to :membership
  belongs_to :assigned_task
  has_one :project, through: :assigned_task
  has_one :task, through: :assigned_task, source: :task
  has_one :user, through: :membership

  validates :notes, length: { maximum: 255 }
  validates :minutes, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 1440 }
  validates :membership, presence: true
  validates :assigned_task, presence: true
  validates :assigned_task_id, presence: true
  validates :date_worked, presence: true
end

app/controllers/time_regs_controller.rb
class TimeRegsController < ApplicationController
  before_action :authenticate_user!

  require 'activerecord-import/base'
  require 'csv'
  include TimeRegsHelper

  def index
    begin
      @chosen_date = params[:date] ? Date.parse(params[:date]) : Date.today
    rescue Date::Error
      @chosen_date = Date.today
    end
    @time_regs = current_user.time_regs.where('date(date_worked) = ?', @chosen_date).includes(:project,
                                                                                              :assigned_task).order(created_at: :desc)
    @total_minutes_day = @time_regs.sum(:minutes)
    @minutes_by_day = minutes_by_day_of_week(@chosen_date, current_user)
    @projects = current_user.projects
    @time_reg = TimeReg.new(date_worked: Date.today)

    # calculate the start and end date of the week of @chosen_date
    start_date = @chosen_date.beginning_of_week
    end_date = @chosen_date.end_of_week

    @time_regs_week = current_user.time_regs.where('date(date_worked) BETWEEN ? AND ?', start_date, end_date)
    @total_minutes_week = @time_regs_week.sum(:minutes)
  end

  def new
    @projects = current_user.projects
    @time_reg = TimeReg.new
  end

  def create
    # gives the time_reg all the attributes
    if Project.exists?(time_reg_params[:project_id])
      @project = Project.find(time_reg_params[:project_id])
      @time_reg = @project.time_regs.build(time_reg_params.except(:project_id))
      membership = @project.memberships.find_by(user_id: current_user.id, project_id: @project.id)
      @time_reg.membership_id = membership.id
    else
      @time_reg = TimeReg.new(time_reg_params.except(:project_id))
    end

    @time_reg.active = @time_reg.minutes == 0 # start as active?
    @time_reg.updated = Time.now

    if @time_reg.save
      flash[:notice] = 'Time entry has been created'
      redirect_to time_regs_path
    else
      @show_new = true
      @chosen_date = params[:date] ? Date.parse(params[:date]) : Date.today
      @time_regs = current_user.time_regs.where('date(date_worked) = ?', @chosen_date).includes(:project,
                                                                                                :assigned_task).order(created_at: :desc)

      @projects = current_user.projects

      @total_minutes_day = @time_regs.sum(:minutes)
      @minutes_by_day = minutes_by_day_of_week(@chosen_date, current_user)

      # calculate the start and end date of the week of @chosen_date
      start_date = @chosen_date.beginning_of_week
      end_date = @chosen_date.end_of_week

      @time_regs_week = current_user.time_regs.where('date(date_worked) BETWEEN ? AND ?', start_date, end_date)
      @total_minutes_week = @time_regs_week.sum(:minutes)

      render :index, status: :unprocessable_entity
    end
  end

  def edit
    @time_reg = TimeReg.find(params[:id])
    @projects = current_user.projects
    @assigned_tasks = Task.joins(:assigned_tasks)
                          .where(assigned_tasks: { project_id: @time_reg.project.id })
                          .pluck(:name, 'assigned_tasks.id')
  end

  def update
    @time_reg = TimeReg.find(params[:id])

    if @time_reg.update(time_reg_params.except(:project_id))
      redirect_to time_regs_path
      flash[:notice] = 'Time entry has been updated'
    else
      @projects = current_user.projects
      @assigned_tasks = Task.joins(:assigned_tasks)
                            .where(assigned_tasks: { project_id: @time_reg.project.id })
                            .pluck(:name, 'assigned_tasks.id')

      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @time_reg = TimeReg.find(params[:id])

    if @time_reg.destroy
      redirect_to time_regs_path
      flash[:notice] = 'Time entry has been deleted'
    else
      @projects = current_user.projects
      @assigned_tasks = Task.joins(:assigned_tasks)
                            .where(assigned_tasks: { project_id: @time_reg.project.id })
                            .pluck(:name, 'assigned_tasks.id')

      flash[:alert] = 'cannot delete time entry'
      render :edit, status: :unprocessable_entity
    end
  end

  def toggle_active
    @time_reg = TimeReg.find(params[:time_reg_id])
    @project = @time_reg.project

    if @time_reg.minutes < 1440
      # if time_reg is active, it toggles off and updates the minutes += the minutes passed since the timer started
      if @time_reg.active
        new_timestamp = Time.now

        old_time = @time_reg.updated.to_i
        new_time = new_timestamp.to_i

        worked_minutes = (new_time - old_time) / 60

        if (@time_reg.minutes + worked_minutes) < 1440
          @time_reg.minutes += worked_minutes
        else
          @time_reg.minutes = 1440
        end

        @time_reg.active = false
      # if not active, it starts the timer
      else
        @time_reg.updated = Time.now
        @time_reg.active = true
      end

      # tries to save the changes
      if @time_reg.save
        redirect_to time_regs_path
      else
        redirect_to time_regs_path
      end
    else
      redirect_to time_regs_path
    end
  end

  # exports the time_regs in a project to a .CSV
  def export
    project = Project.find(params[:project_id])
    client = project.client
    time_regs = project.time_regs.includes(
      :task,
      :user,
      membership: [:user],
      assigned_task: %i[project task],
      project: :client
    )
    csv_data = CSV.generate(headers: true) do |csv|
      # Add CSV header row
      csv << ['date', 'client', 'project', 'task', 'notes', 'minutes', 'first name', 'last name', 'email']
      # Add CSV data rows for each time_reg
      time_regs.each do |time_reg|
        csv << [time_reg.date_worked, client.name, project.name, time_reg.assigned_task.task.name,
                time_reg.notes, time_reg.minutes, time_reg.user.first_name, time_reg.user.last_name, time_reg.user.email]
      end
    end
    send_data csv_data, filename: "#{Time.now.to_i}_time_regs_for_#{project.name}.csv"
  end

  # changes the selection tasks to show tasks from a specific project
  def update_tasks_select
    @tasks = Task.joins(:assigned_tasks).where(assigned_tasks: { project_id: params[:project_id] }).pluck(:name,
                                                                                                          'assigned_tasks.id')
    render partial: '/time_regs/select', locals: { tasks: @tasks }
  end

  private

  def time_reg_params
    params.require(:time_reg).permit(:notes, :minutes, :assigned_task_id, :date_worked, :project_id)
  end
end

app/helpers/time_regs_helper.rb
module TimeRegsHelper
  # converts minutes to "0:00" format
  def convert_time_int(minutes)
    return nil if minutes.nil?

    hours = minutes / 60
    minutes = minutes % 60

    return "#{hours}:#{minutes}" if minutes > 9

    "#{hours}:0#{minutes}"
  end

  def minutes_by_day_of_week(date, user)
    start_of_week = date.beginning_of_week
    end_of_week = date.end_of_week

    time_regs = user.time_regs.where(date_worked: start_of_week..end_of_week)

    minutes_by_day = Hash.new(0)
    time_regs.each do |time_reg|
      day_of_week = time_reg.date_worked.strftime('%A')
      minutes_by_day[day_of_week] += time_reg.minutes
    end

    minutes_by_day
  end
end

app/views/time_regs/_new.html.erb
<div class="flex flex-col items-center p-4">
  <div class="max-w-md">
    <div class="p-4 my-4" data-controller="time-tasks">
      <h1 class="font-bold text-2xl mb-4">New time entry:</h1>
      <%= form_with(model: @time_reg) do |form| %>
      <%= hidden_field_tag :date, @chosen_date %>
        <div class="mb-4">
          <%= form.label :project_id, class: 'block text-gray-700 text-sm font-bold mb-2' %>       
          <%= form.collection_select :project_id, @projects , :id, :name, { include_blank: "select a project:"}, {class: 'w-full rounded-md p-2 border border-gray-300 focus:ring-1 focus:ring-seaGreenDark focus:border-seaGreenDark ring-offset-1 ring-offset-white', id: 'timeproject-select'}  %>
          <% @time_reg.errors.full_messages_for(:membership).any? do |message| %>
            <div class="text-red-600 text-xs italic mt-1">Please select a project</div>
          <% end %>
        </div>

        <div class="mb-4">
          <%= form.label :assigned_task_id, class: 'block text-gray-700 text-sm font-bold mb-2' %>
          <%= form.collection_select :assigned_task_id, {}, :id, :name, {}, {class: 'w-full rounded-md p-2 border border-gray-300 focus:ring-1 focus:ring-seaGreenDark focus:border-seaGreenDark ring-offset-1 ring-offset-white', id: 'timetask-select'}  %>
          <% @time_reg.errors.full_messages_for(:assigned_task_id).each do |message| %>
            <div class="text-red-600 italic text-xs mt-1">Please select a task</div>
          <% end %>
        </div>

        <div class="mb-4">
          <%= form.label :notes, class: 'block text-gray-700 text-sm font-bold mb-2' %>       
          <% @time_reg.errors.full_messages_for(:notes).each do |message| %>
            <div  class="text-red-600 text-xs italic mt-1"><%= message %></div>
          <% end %>
          <%= form.text_area :notes, class: 'w-full rounded-md p-2 border border-gray-300 focus:ring-1 focus:ring-seaGreenDark focus:border-seaGreenDark ring-offset-1 ring-offset-white' %>
        </div>

        <div class="mb-4">
          <%= form.label :minutes, class: 'block text-gray-700 text-sm font-bold mb-2' %>
          <% @time_reg.errors.full_messages_for(:minutes).each do |message| %>
            <div class="text-red-600 italic text-xs mt-1"><%= message %></div>
          <% end %>
          <%= form.number_field :minutes, value: 0, class: 'w-full rounded-md p-2 border border-gray-300 focus:ring-1 focus:ring-seaGreenDark focus:border-seaGreenDark ring-offset-1 ring-offset-white' %>
        </div>

         <div class="mb-4">
          <%= form.label :date_worked, class: 'block text-gray-700 text-sm font-bold mb-2' %>
          <% @time_reg.errors.full_messages_for(:date_worked).each do |message| %>
            <div class="text-red-600 italic text-xs mt-1"><%= message %></div>
          <% end %>
          <div class="flex justify-between">
            <%= form.date_field :date_worked, class: 'w-full rounded-md p-2 border border-gray-300 focus:ring-1 focus:ring-seaGreenDark focus:border-seaGreenDark ring-offset-1 ring-offset-white' %>
          </div>
        </div>

        <div class="flex justify-center mt-8 px-4">
          <span class="rounded bg-seaGreen p-2 m-2 shadow text-white hover:bg-seaGreenDark">
            <%= form.submit class: '' %>          
          </span>
          <div data-action="click->modal#toggle" class="cursor-pointer rounded bg-tastyWhiteLite p-2 m-2 hover:bg-red-100 shadow">
            Cancel
          </div> 
        </div>
      <% end %> 
    </div>
  </div>  
</div>

app/views/time_regs/_select.html.erb
<% tasks.each do |task| %>
  <option value="<%= task.last %>"><%= task.first %></option>
<% end %>

app/views/time_regs/_time_reg.html.erb
<div class=" p-4 divide-y-2 bg-tastyWhite"  <%= 'data-controller=refresh-minutes' if time_reg.active %> > 
  <div class="flex"> 
    <div class="grow">
      <b class="mr-2"> <%= time_reg.project.name %></b>(<%= time_reg.project.client.name %>)
      <br>
      <%= time_reg.notes %>
    </div>
    <div class="flex items-center justify-between">
      <span class="font-semibold" data-refresh-minutes-target="output" ><%= convert_time_int(time_reg.minutes)%></span>
      <%= link_to edit_time_reg_path(time_reg), class: '' do %>
        <div class="rounded bg-blue-200 p-2 m-2 hover:bg-blue-300 whitespace-nowrap flex space-x-2">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
            <path stroke-linecap="round" stroke-linejoin="round" d="M10.343 3.94c.09-.542.56-.94 1.11-.94h1.093c.55 0 1.02.398 1.11.94l.149.894c.07.424.384.764.78.93.398.164.855.142 1.205-.108l.737-.527a1.125 1.125 0 011.45.12l.773.774c.39.389.44 1.002.12 1.45l-.527.737c-.25.35-.272.806-.107 1.204.165.397.505.71.93.78l.893.15c.543.09.94.56.94 1.109v1.094c0 .55-.397 1.02-.94 1.11l-.893.149c-.425.07-.765.383-.93.78-.165.398-.143.854.107 1.204l.527.738c.32.447.269 1.06-.12 1.45l-.774.773a1.125 1.125 0 01-1.449.12l-.738-.527c-.35-.25-.806-.272-1.203-.107-.397.165-.71.505-.781.929l-.149.894c-.09.542-.56.94-1.11.94h-1.094c-.55 0-1.019-.398-1.11-.94l-.148-.894c-.071-.424-.384-.764-.781-.93-.398-.164-.854-.142-1.204.108l-.738.527c-.447.32-1.06.269-1.45-.12l-.773-.774a1.125 1.125 0 01-.12-1.45l.527-.737c.25-.35.273-.806.108-1.204-.165-.397-.505-.71-.93-.78l-.894-.15c-.542-.09-.94-.56-.94-1.109v-1.094c0-.55.398-1.02.94-1.11l.894-.149c.424-.07.765-.383.93-.78.165-.398.143-.854-.107-1.204l-.527-.738a1.125 1.125 0 01.12-1.45l.773-.773a1.125 1.125 0 011.45-.12l.737.527c.35.25.807.272 1.204.107.397-.165.71-.505.78-.929l.15-.894z" />
            <path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
          </svg>
          Edit
        </div>
      <% end %>

      <% if time_reg.active %>
        <%= button_to time_reg_toggle_active_path(time_reg_id: time_reg.id), method: :patch, class: "mr-2" do %>
          <div class="bg-red-300 hover:bg-red-400 p-2 m-2 flex space-x-2 rounded text-black">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
              <path stroke-linecap="round" stroke-linejoin="round" d="M14.25 9v6m-4.5 0V9M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
            </svg>
            Stop
          </div>
        <% end %>
      <% else %>
        <%= button_to time_reg_toggle_active_path(time_reg_id: time_reg.id), method: :patch, class: "mr-2 text-bold" do %>
          <div class="bg-seaGreen hover:bg-seaGreenDark p-2 m-2 flex space-x-2 rounded text-white">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
              <path stroke-linecap="round" stroke-linejoin="round" d="M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
              <path stroke-linecap="round" stroke-linejoin="round" d="M15.91 11.672a.375.375 0 010 .656l-5.603 3.113a.375.375 0 01-.557-.328V8.887c0-.286.307-.466.557-.327l5.603 3.112z" />
            </svg>
            Start
          </div>
        <% end %>
      <% end %>
    </div> 
    <!-- values for the dynamic minutes updating -->
    <span data-minutes="<%= time_reg.minutes %>" data-refresh-minutes-target="minutes" class="hidden"></span>
    <span data-updated="<%= time_reg.updated.iso8601 %>" data-refresh-minutes-target="updated" class="hidden"></span> 
    <!-- Add more cells for other TimeEntry attributes -->
  </div>
</div>

app/views/time_regs/edit.html.erb
<div class="flex flex-col items-center pt-4">
  <div class="max-w-md">
    <div class="p-1 my-4">
    <h1 class="font-bold text-2xl mb-4">Edit time entry:</h1>

    <div class="p-1 my-4" data-controller="time-tasks">
      <%= form_with(model: @time_reg) do |form| %>
        <div class="field my-4 w-80">
          <%= form.label :project_id, class: 'block text-gray-700 text-sm font-bold mb-2'  %>       
          <%= form.collection_select :project_id, @projects , :id, :name, { selected: @time_reg.project.id }, { class: 'w-full rounded-md p-2 border border-gray-300 focus:ring-1 focus:ring-seaGreenDark focus:border-seaGreenDark ring-offset-1 ring-offset-white', id: 'timeproject-select' } %>
          <% @time_reg.errors.full_messages_for(:project_id).each do |message| %>
            <div class="text-red-600 text-xs italic mt-1"><%= message %></div>
          <% end %>
        </div>

        <div class="field my-4 w-80">
          <%= form.label :assigned_task_id, class: 'block text-gray-700 text-sm font-bold mb-2' %>
          <%= form.collection_select :assigned_task_id, @assigned_tasks, :last, :first, {}, {class: 'w-full rounded-md p-2 border border-gray-300 focus:ring-1 focus:ring-seaGreenDark focus:border-seaGreenDark ring-offset-1 ring-offset-white', id: 'timetask-select'}  %>
          <% @time_reg.errors.full_messages_for(:assigned_task_id).each do |message| %>
            <div class="text-red-600 text-xs italic mt-1"><%= message %></div>
          <% end %>
        </div>

        <div class="field my-4">
          <%= form.label :notes, class: 'block text-gray-700 text-sm font-bold mb-2' %>       
          <% @time_reg.errors.full_messages_for(:notes).each do |message| %>
            <div class="text-red-600 text-xs italic mt-1"><%= message %></div>
          <% end %>
          <%= form.text_area :notes, class: 'w-full rounded-md p-2 border border-gray-300 focus:ring-1 focus:ring-seaGreenDark focus:border-seaGreenDark ring-offset-1 ring-offset-white' %>
        </div>

        <div class="field my-45">
          <%= form.label :minutes, class: 'block text-gray-700 text-sm font-bold mb-2' %>
          <% @time_reg.errors.full_messages_for(:minutes).each do |message| %>
            <div class="text-red-600 text-xs italic mt-1"><%= message %></div>
          <% end %>
          <%= form.number_field :minutes, class: 'w-full rounded-md p-2 border border-gray-300 focus:ring-1 focus:ring-seaGreenDark focus:border-seaGreenDark ring-offset-1 ring-offset-white'  %>
        </div>

        <div class="field my-4 mb-10">  
          <%= form.label :date_worked, class: 'block text-gray-700 text-sm font-bold mb-2' %>
          <% @time_reg.errors.full_messages_for(:date_worked).each do |message| %>
            <div class="text-red-600 italic text-xs mt-1"><%= message %></div>
          <% end %>     
          <div class="flex justify-between">
            <%= form.date_field :date_worked, class: 'w-full rounded-md p-2 border border-gray-300 focus:ring-1 focus:ring-seaGreenDark focus:border-seaGreenDark ring-offset-1 ring-offset-white' %>
          </div>
        </div>

        <div class="actions text-center">
          <span class="rounded bg-seaGreen p-2 m-2 hover:bg-seaGreenDark shadow text-white">
           <%= form.submit class: '' %>
          </span>
          <%= link_to 'Cancel', :back, class: "rounded bg-tastyWhiteLite p-2 m-2 hover:bg-red-100 shadow mt-6" %>
        </div>   
      <% end %> 
    </div>

    </div>

    <div class="text-center p-1 m-1">
      <%= 
        link_to "Delete time entry ", time_reg_path(@time_reg), 
          class: 'rounded bg-red-400 p-2 hover:bg-red-500', 
          data:{
            turbo_method: :delete,
            turbo_confirm: "Are you sure?"
          }
      %>        
    </div>
  </div>
</div>

app/views/time_regs/index.html.erb
<% t = Time.new %>

<div class="flex flex-row self-center m-auto w-full 2xl:w-3/4 " data-controller="modal">
  <div class=" justify-items-center max-[800px]:hidden mt-[5vh]">
    <div class="content-center self-center justify-items-center ">

      <div class="flex flex-col self-center ">
        <div class="text-xs mt-2 m-auto self-center">
          <!-- NORMAL BUTTON FOR SHOWING THE NEW FORM-->
          <button data-action="click->modal#toggle">
            <div class="bg-seaGreen hover:bg-seaGreenDark h-16 w-16 px-1 py-1 rounded-xl self-center m-auto ">
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2.5" stroke="white" class="w-14 h-14 self-center">
                <path stroke-linecap="round" stroke-linejoin="round" d="M12 4.5v15m7.5-7.5h-15" />
              </svg>
            </div>
            <p class='mt-4 text-lg'>
            Track time</p>
          </button>
        </div>
      </div>
    </div>
  </div>

  <div class="flex flex-col grow mx-8">
    <div class="flex w-full justify-between">
      <div class=" flex space-x-4">
        <%= link_to root_path(date: @chosen_date - 1.day) do %>
          <div class="p-2 rounded-lg bg-seaGreen text-white">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
              <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 19.5L8.25 12l7.5-7.5" />
            </svg>
          </div>
        <% end %>
        <%= link_to root_path(date: @chosen_date + 1.day) do %>
          <div class="p-2 rounded-lg bg-seaGreen text-white">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
              <path stroke-linecap="round" stroke-linejoin="round" d="M8.25 4.5l7.5 7.5-7.5 7.5" />
            </svg>
          </div>
        <% end %>

        <div class="flex lg:text-3xl text-xl w-3/4  max-[800px]:hidden">
          <% if @chosen_date == Date.today %>
            <p class="bold ml-4 mr-4">
            Today: 
            </p>
          <% end %>
          <p class="  ">
          <%= @chosen_date.strftime("%A, %d %B") %>
          </p>
        </div>
      </div>
      <div class="col-span-3">

        <%= form_tag(root_path, method: "get", class: "flex space-x-2") do %>
          <%= date_field_tag :date, @chosen_date, class: 'focus:ring-1 focus:ring-seaGreenDark focus:border-seaGreenDark ring-offset-1 ring-offset-white' %>
          <div class="self-center ml-2 bg-seaGreen hover:bg-seaGreenDark rounded-xl self-center m-auto p-2 text-white flex">
            <%= submit_tag "Go to date", class: "" %>
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class=" ml-2 mr-2 w-4 h-4 self-center">
              <path stroke-linecap="round" stroke-linejoin="round" d="M8.25 4.5l7.5 7.5-7.5 7.5" />
            </svg>
          </div>

        <% end %>
      </div>
    </div>

    <!-- MOBILE BUTTON FOR SHOWING THE NEW FORM-->
    <div class=" min-[800px]:hidden ">
      <div class="">
        <button data-action="click->modal#toggle">
          <div class="bg-seaGreen mt-4 h-8 w-screen px-1 py-1 rounded-xl self-stretch text-white  ">
            Track time
          </div>
        </button>
      </div>
    </div>

    <div class="flex flex-row items-center content-center mt-6 max-[640px]:hidden max-[800px]:my-2">
      <% Date::DAYNAMES.rotate.each_with_index do |day, i| %>
        <div class="grid grow max-[800px]:text-xs <%= 'border-b-2 border-red-300' if @chosen_date.wday == (i+1)%7 %>">
          <% current_day_index = i + 1 %>

          <% if @chosen_date.wday == 0 %>
            <% diff =  current_day_index - 7%>
          <% else %>
            <% diff = current_day_index - @chosen_date.wday %>
          <% end %>

          <%= link_to day, root_path(date: @chosen_date + diff.days) %><br>
          <% day_minutes = @time_regs_week.select{ |tr| tr.date_worked.wday == (i+1) % 7 }.sum(&:minutes) %>
          <%= format_duration(day_minutes) %>

        </div>
      <% end %>
      <div class="grid grow">
        Week total
        <br />
        <%= format_duration(@total_minutes_week) %>
      </div>
    </div>

    <!-- DIV SHOWING THE NEW FORM-->
    <div data-modal-target="modal" class="modal <%= "hidden" unless @show_new %> fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
      <div class="modal-content bg-white rounded-lg overflow-hidden shadow-xl transform transition-all" data-action="click->modal#preventClose">
        <%= render "time_regs/new", time_reg: @time_reg, projects: @projects %>
      </div>
    </div>
  
    <div class="border-y-2 divide-y-2">
      <%= render @time_regs %>
    </div>

    <div class='text-end mt-6 mr-24'>
      Total: <%= format_duration(@total_minutes_day) %>
    </div>
  </div>
</div>
</div>

app/views/time_regs/new.html.erb
<%= render 'new' %>

app/views/time_regs/oldindex.html.erb
<div class="flex flex-col items-center pt-4 mb-28">
  <div class="max-w-md md:min-w-custom35" data-controller="dynamic-minutes" data-dynamic-minutes-user-id="<%= current_user.id %>" id="time-view">
    <%= render @time_regs %>
  </div>
  <div class="flex justify-evenly">
      <%= link_to "New time-entry", new_time_reg_path, class: 'rounded bg-blue-200 p-2 mr-6 hover:bg-blue-300' %>
  </div>
</div>