config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'time_regs#index'

  resources :project_reports do
    patch :update_group
    collection do
      get 'update_projects_selection'
      get 'update_members_checkboxes'
      get 'update_tasks_checkboxes'
      post 'export'
    end
  end

  resources :user_reports do
    patch :update_group
    collection do
      post 'export'
      get 'update_projects_checkboxes'
      get 'update_tasks_checkboxes'
    end
  end

  resources :clients

  resources :tasks

  match 'projects/import' => 'projects#import', :via => :post
  resources :time_regs do
    patch :toggle_active
    collection do
      get 'export'
      post 'import'
      get 'update_tasks_select'
      get 'new_modal', to: 'time_regs#new', as: :new_modal
    end
  end

  resources :projects do
    resources :memberships
    resources :assigned_tasks
    get 'export', to: 'projects#export', as: 'export_project_time_reg'
  end
end

app/models/client.rb
class Client < ApplicationRecord
  validates :name, format: { without: /\r|\n/, message: 'Line breaks are not allowed' }
  validates :name, presence: true, length: { minimum: 2, maximum: 30 }, uniqueness: true
  validates :description, presence: true, length: { minimum: 2, maximum: 100 }

  has_many :projects
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :authenticate_user!

  def index
    @clients = Client.all
  end

  def show
    @client = Client.find(params[:id])
    @projects = current_user.projects.where(projects: { client_id: @client.id })
  end

  def new
    @client = Client.new
  end

  def create
    @client = Client.new(client_params)

    if @client.save
      redirect_to @client
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @client = Client.find(params[:id])
  end

  def update
    @client = Client.find(params[:id])

    if @client.update(client_params)
      redirect_to @client
      flash[:notice] = 'client has been updated'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @client = Client.find(params[:id])

    # checks the confirmation field before trying to delete
    if delete_params[:confirmation] == 'DELETE'
      if @client.destroy
        flash[:notice] = 'Client deleted'
        redirect_to clients_path
      else
        flash[:alert] = 'Could not delete client'
        redirect_to edit_client_path(@client)
      end
    else
      flash[:alert] = 'Invalid confirmation'
      redirect_to edit_client_path(@client)
    end
  end

  private

  def client_params
    params.require(:client).permit(:name, :description)
  end

  def delete_params
    params.permit(:confirmation, :id)
  end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.erb
<%= form_with model: @client do |form|%>
  <br>
  <div>
    <%= form.label :name, class: 'block text-gray-700 font-bold mb-2' %> 
    <%= form.text_area :name, class: "w-full rounded-md p-2 border border-gray-300 mr-8 focus:ring-1 focus:ring-seaGreenDark focus:border-seaGreenDark ring-offset-1 ring-offset-white" %>
    <% @client.errors.full_messages_for(:name).each do |message|%>
      <div class="text-red-600 italic text-xs mt-1">
        <%= message %>
      </div>
    <% end %>
  </div>
  <br>
  <div>
    <%= form.label :description, class: 'block text-gray-700 font-bold mb-2' %>
    <%= form.text_area :description, class: "w-full rounded-md p-2 border border-gray-300 mr-8 focus:ring-1 focus:ring-seaGreenDark focus:border-seaGreenDark ring-offset-1 ring-offset-white" %>
    <% @client.errors.full_messages_for(:description).each do |message|%>
      <div class="text-red-600 italic text-xs mt-1">
        <%= message %>
      </div>            
    <% end %>
  </div>  
  <br>
  <div class="actions text-center p-1 m-1">
    <span class="rounded bg-seaGreen p-2 hover:bg-seaGreenDark text-white">
      <%= form.submit class: "" %>
    </span>
    <%= link_to 'Cancel', :back, class: "rounded bg-tastyWhiteLite p-2 m-2 hover:bg-red-100 shadow" %>
  </div>
<% end %>

app/views/clients/_remove.html.erb
<div class="mt-5 mb-5 bg-tastyWhiteLite border border-gray-400 rounded p-2">
  <div class="">
    <h4 class="font-semibold text-center">CAREFUL! this action will:</h4>
    <div class="flex justify-center">
      <ul class="italic">
        <li>- Delete the client permanently</li>
      </ul>              
    </div>
  </div>
  <br>
  <% if client.projects.count < 1%>
    <%= form_tag(client_path(client), method: :delete) do %>
        <span class="flex justify-center pb-2">Please enter "<span class="font-semibold">DELETE</span>" to confirm</span>
        <div class="flex justify-center">
        <%= text_field_tag :confirmation, nil, class: "form-control" %>
        <%= submit_tag "Delete client", class: "ml-2 bg-red-400 p-2 hover:bg-red-500 rounded" %>
        </div>
    <% end %>
  <% else %>
    <p class="text-center">Cannot delete client with active projects</p>
  <% end %>
</div>  

app/views/clients/edit.html.erb
<div class="flex flex-col items-center pt-4">
  <div class="max-w-md md:min-w-custom35 my-4" data-controller="collapse-delete">
    <div class='flex justify-between' >
      <h1 class="font-medium italic text-2xl ml-4">Edit <%= @client.name %></h1><br>
      <button data-action="click->collapse-delete#deleteDiv" 
        class="rounded bg-tastyWhiteLite border border-gray-400 p-2 hover:bg-red-400" 
        data-task-id="delete-button">Delete client
      </button>
    </div>
    <div class="hidden" data-collapse-delete-target="toggleDiv">
      <%= render "clients/remove", client: @client %>
    </div>
    <%= render "form", client: @client%>
  </div>
</div>

app/views/clients/index.html.erb
<div class="flex flex-col items-center pt-4">
  <div class="max-w-md md:min-w-custom35">
    <div class="p-1 my-2 pt-2">
      <h1 class="font-bold text-3xl italic pb-4"><span class="ml-2">Clients</span> </h1>
      <% @clients.each do |client| %>
          <div class="border-b text-gray-700 border-gray-300 pb-2 pt-2">
          <%= link_to client.name, client, class: 'text-left' %>
        </div>
      <% end %>
    </div>
    <div class="pt-10 flex justify-evenly">
        <%= link_to "New client", new_client_path, class: 'rounded bg-seaGreen p-2 hover:bg-seaGreenDark text-white' %>
    </div>  
  </div>
</div>

app/views/clients/new.html.erb
<div class="flex flex-col items-center pt-4">
  <div class="max-w-md md:min-w-custom35 p-1 my-4">
    <h1 class="font-medium italic text-2xl ml-4 mb-2">New client</h1>
    <%= render "form", client: @client%>
  </div>
</div>

app/views/clients/show.html.erb
<div class="flex flex-col items-center pt-4">
  <div class="max-w-md md:min-w-custom35">
    <div class='flex justify-between'>
      <p class='text-3xl mr-4'> <%= @client.name %></p> 
      <%= link_to edit_client_path(@client), class: "pl-3 pr-3 p-2 mr-10 rounded bg-blue-200 hover:bg-blue-300 flex justify-space-x-2" do %>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
          <path stroke-linecap="round" stroke-linejoin="round" d="M10.343 3.94c.09-.542.56-.94 1.11-.94h1.093c.55 0 1.02.398 1.11.94l.149.894c.07.424.384.764.78.93.398.164.855.142 1.205-.108l.737-.527a1.125 1.125 0 011.45.12l.773.774c.39.389.44 1.002.12 1.45l-.527.737c-.25.35-.272.806-.107 1.204.165.397.505.71.93.78l.893.15c.543.09.94.56.94 1.109v1.094c0 .55-.397 1.02-.94 1.11l-.893.149c-.425.07-.765.383-.93.78-.165.398-.143.854.107 1.204l.527.738c.32.447.269 1.06-.12 1.45l-.774.773a1.125 1.125 0 01-1.449.12l-.738-.527c-.35-.25-.806-.272-1.203-.107-.397.165-.71.505-.781.929l-.149.894c-.09.542-.56.94-1.11.94h-1.094c-.55 0-1.019-.398-1.11-.94l-.148-.894c-.071-.424-.384-.764-.781-.93-.398-.164-.854-.142-1.204.108l-.738.527c-.447.32-1.06.269-1.45-.12l-.773-.774a1.125 1.125 0 01-.12-1.45l.527-.737c.25-.35.273-.806.108-1.204-.165-.397-.505-.71-.93-.78l-.894-.15c-.542-.09-.94-.56-.94-1.109v-1.094c0-.55.398-1.02.94-1.11l.894-.149c.424-.07.765-.383.93-.78.165-.398.143-.854-.107-1.204l-.527-.738a1.125 1.125 0 01.12-1.45l.773-.773a1.125 1.125 0 011.45-.12l.737.527c.35.25.807.272 1.204.107.397-.165.71-.505.78-.929l.15-.894z" />
          <path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
        </svg>
        Edit
      <% end %>
    </div>

    <p class='text-md'> <%= @client.description %></p>

    <div class="pt-10">
      <h1 class="font-medium border-b border-gray-300 text-lg italic pb-2">Your projects </h1>
      <%= render @projects %>  
    </div>
    <br>
    <div class="flex justify-evenly">
      <%= link_to "New Project", new_project_path, class: 'rounded bg-seaGreen p-2 hover:bg-seaGreenDark text-white'%>
    </div>
  </div>
</div>