config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'time_regs#index'

  resources :project_reports do
    patch :update_group
    collection do
      get 'update_projects_selection'
      get 'update_members_checkboxes'
      get 'update_tasks_checkboxes'
      post 'export'
    end
  end

  resources :user_reports do
    patch :update_group
    collection do
      post 'export'
      get 'update_projects_checkboxes'
      get 'update_tasks_checkboxes'
    end
  end

  resources :clients

  resources :tasks

  match 'projects/import' => 'projects#import', :via => :post
  resources :time_regs do
    patch :toggle_active
    collection do
      get 'export'
      post 'import'
      get 'update_tasks_select'
      get 'new_modal', to: 'time_regs#new', as: :new_modal
    end
  end

  resources :projects do
    resources :memberships
    resources :assigned_tasks
    get 'export', to: 'projects#export', as: 'export_project_time_reg'
  end
end

app/models/project.rb
class Project < ApplicationRecord
  validates :name, presence: true, length: { minimum: 2, maximum: 30 }, uniqueness: true
  validates :description, presence: true, length: { minimum: 2, maximum: 100 }

  belongs_to :client
  has_many :memberships, dependent: :destroy
  has_many :users, through: :memberships
  has_many :time_regs, through: :memberships
  has_many :assigned_tasks, dependent: :destroy
  has_many :tasks, through: :assigned_tasks
end

app/models/project_report.rb
class ProjectReport < ApplicationRecord
  validates_presence_of :timeframe, :client_id, :project_id, :group_by
  validate :timeframe_dates_present, if: :custom_timeframe?
  validate :validate_member_ids_presence
  validate :valdiate_task_ids_presence

  # custom validations

  def custom_timeframe?
    timeframe == 'custom'
  end

  def timeframe_dates_present
    return unless date_start.blank? || date_end.blank?

    errors.add(:custom_timeframe, 'requires both start and end dates to be present')
  end

  def validate_member_ids_presence
    return unless member_ids.blank? || member_ids.all?(&:empty?)

    errors.add(:member_ids, 'Please select atleast one member')
  end

  def valdiate_task_ids_presence
    return unless task_ids.blank? || task_ids.all?(&:empty?)

    errors.add(:task_ids, 'Please select atleast one task')
  end
end

app/controllers/project_reports_controller.rb
class ProjectReportsController < ReportsController
  GROUPES = { 'Task' => 'task', 'Date' => 'date', 'User' => 'user' } # columns to group report by
  START_GROUP = 'date' # standard grouping when creating new project report

  # show report
  def show
    @show_edit_form = false
    @report = ProjectReport.find(params[:id])
    @time_regs = get_time_regs(@report, @report.member_ids, @report.project_id, @report.task_ids)
    @grouped_report = group_time_regs(@time_regs, @report.group_by)
    @groupes = GROUPES

    # data for the edit form
    @timeframeOptions = get_timeframe_options
    @clients = Client.all
    @projects = @clients.find(@report.client_id).projects
    project = @projects.find(@report.project_id)
    @members = project.users
    @tasks = project.tasks
    @show_custom_timeframe = @report.timeframe == 'custom'
  end

  def update
    @report = ProjectReport.find(params[:id])

    # saves old data to render every time_reg if needed
    @time_regs = get_time_regs(@report, @report.member_ids, @report.project_id, @report.task_ids)
    @grouped_report = group_time_regs(@time_regs, @report.group_by)

    # clear arrays if no new data
    @report.member_ids = [] unless project_report_params[:member_ids].present?
    @report.task_ids = [] unless project_report_params[:task_ids].present?

    @report.assign_attributes(project_report_params.except(:project_id))

    # only adds project_id if it is a valid project (avoids error if user tries to update with "select a project" value)
    @report.project_id = Project.exists?(project_report_params[:project_id]) ? project_report_params[:project_id] : nil

    # sets new dates
    set_dates(@report) unless @report.timeframe == 'custom'

    # tries to update the report with new values
    if @report.save
      redirect_to @report
    else
      # sets all data the page needs when re-rendering with errors in the form
      @show_edit_form = true
      @groupes = GROUPES
      @show_custom_timeframe = @report.timeframe == 'custom'
      @timeframeOptions = get_timeframe_options
      @clients = Client.all
      @projects = @report.client_id.present? ? @clients.find(@report.client_id).projects : []

      if @report.project_id.present?
        project = Project.find(@report.project_id)
        @members = @report.member_ids.present? ? project.users : []
        @tasks = @report.task_ids.present? ? project.tasks : []
      else
        @members = []
        @tasks = []
      end
      render :show, status: :unprocessable_entity
    end
  end

  def new
    # data for the new form
    @report = ProjectReport.new
    @show_custom_timeframe = false
    @timeframeOptions = get_timeframe_options
    @clients = Client.all
    @projects = []
    @members = []
    @tasks = []
  end

  def create
    # creates a new report and sets values from form
    @report = ProjectReport.new(project_report_params)
    set_dates(@report) unless @report.timeframe == 'custom'
    @report.group_by = START_GROUP # standard grouping from const

    # tries to save the new report
    if @report.save
      redirect_to @report
    else
      # else: re-renders the new-form with errors
      @show_custom_timeframe = @report.timeframe == 'custom'
      @timeframeOptions = get_timeframe_options
      @clients = Client.all
      @projects = @report.client_id.present? ? Project.where(client_id: @report.client_id) : []
      if @report.project_id.present?
        project = Project.find(@report.project_id)
        @members = @report.member_ids.present? ? project.users : []
        @tasks = @report.task_ids.present? ? project.tasks : []
      else
        @members = []
        @tasks = []
      end
      render :new, status: :unprocessable_entity
    end
  end

  def update_group
    @report = ProjectReport.find(params[:project_report_id])

    # checks for valid grouping
    if GROUPES.values.include?(params[:group_by])
      @report.group_by = params[:group_by]

      # tries to update the grouping
      if @report.save
        redirect_to @report
      else
        flash[:alert] = 'Could not change the grouping'
        redirect_to @report
      end
    else
      flash[:alert] = 'Invalid group'
      redirect_to @report
    end
  end

  # ********************
  # AJAX form updates *
  # *******************

  # updates the form with projects from a specific client
  # returns a partial
  def update_projects_selection
    projects = Project.where(client_id: params[:client_id])
    render partial: 'projects', locals: { projects: }
  end

  # updates the form with members from a specific project
  # returns a partial
  def update_members_checkboxes
    members = Project.find(params[:project_id]).users
    render partial: 'checkboxes', locals: { report: ProjectReport.new, checkboxes: members, text: 'member' }
  end

  # updates the form with tasks from a specific project
  # returns a partial
  def update_tasks_checkboxes
    tasks = Project.find(params[:project_id]).tasks
    render partial: 'checkboxes', locals: { report: ProjectReport.new, checkboxes: tasks, text: 'task' }
  end

  # permits only valid attributes
  private

  def project_report_params
    params.require(:project_report).permit(:timeframe, :date_start, :date_end, :client_id, :project_id, member_ids: [],
                                                                                                        task_ids: [])
  end
end

app/helpers/project_report_helper.rb
module ProjectReportHelper
end

app/views/project_reports/_checkboxes.html.erb
<div class="" >
  <div class="flex flex-wrap">
    <% if checkboxes.present? %>
      <%= collection_check_boxes :project_report, "#{text}_ids" , checkboxes, :id, :name do |checkbox|%>
        <div class="border mr-8 m-1 p-2 rounded-xl border-gray-300" >
          <%= checkbox.check_box checked: report.send("#{text}_ids".to_sym).include?(checkbox.value.to_s), class: 'text-seaGreenDark focus:ring-seaGreenDark focus:ring-offset-2 focus:ring-opacity-50'%> <!--checks if box was checked earlier-->
          <%= checkbox.label %>      
        </div>
      <% end %>
    <% end %>      
  </div>
</div>

app/views/project_reports/_edit.html.erb
<div class="flex flex-col items-center pt-4 mb-40">
  <div class="max-w-md md:min-w-custom60 bg-tastyWhiteLite rounded border border-gray-300 p-4" data-controller="project-reports">
    <h1 class="text-2xl m-1 font-bold">Time report</h1>
    <br>
    <%= render 'form' %>
  </div>
</div>

app/views/project_reports/_form.html.erb
<%= form_with model: @report do |form| %>
  <div id="timeframe-container">
    <div id="timeframe-error-container">
      <% @report.errors.full_messages_for(:timeframe).each do |message| %>
        <div class="text-red-600 italic text-xs mt-1"><%= message %></div>
      <% end %>
    </div>
    <div id="timeframe-select" class="flex justify-between">
      <%= form.label :timeframe, class: 'block text-gray-700 font-bold mb-2' %>
      <%= form.select :timeframe, @timeframeOptions, {} , {class: 'w-80 mr-8 rounded-md p-2 border border-gray-300 focus:ring-1 focus:ring-seaGreenDark focus:border-seaGreenDark ring-offset-1 ring-offset-white', id: 'timeframe-selection'} %>
    </div>
    <div id="custom-timeframe-error-container">
      <% @report.errors.full_messages_for(:custom_timeframe).each do |message| %>
        <div class="text-red-600 italic text-xs mt-1"><%= message %></div>
      <% end %>
    </div>
    <div id="custom-timeframe-container" class="<%= "hidden" unless @show_custom_timeframe %>">
      <%= render partial: 'timeframe' %>
    </div> 
  </div>
 
  <div id="client-container" class="clear-both pt-10">
    <div id="client-error-container">
      <% @report.errors.full_messages_for(:client_id).each do |message| %>
        <div class="text-red-600 italic text-xs mt-1"><%= message %></div>
      <% end %>
    </div>
    <div class="flex justify-between ">
      <div>
        <%= form.label :client_id, class: 'block text-gray-700 font-bold mb-2' %>
      </div>
      <div>
        <%= form.collection_select :client_id, @clients, :id, :name, {include_blank: 'Select a client' }, {class: 'w-80 mr-8 rounded-md p-2 border border-gray-300 focus:ring-1 focus:ring-seaGreenDark focus:border-seaGreenDark ring-offset-1 ring-offset-white', id: 'client-selection'} %>   
      </div>    
    </div>
  </div>

  <div id="project-container" class="clear-both pt-10">
    <div id="project-error-container">
      <% @report.errors.full_messages_for(:project_id).each do |message| %>
        <div class="text-red-600 italic text-xs mt-1"><%= message %></div>
      <% end %>
    </div>
    <div class="flex justify-between" >
      <div>
        <%= form.label :project_id, class: 'block text-gray-700 font-bold mb-2' %>
      </div>
      <div>
        <!--selection gets dynamically re-filled on client change -->
        <%= form.collection_select :project_id, @projects, :id, :name, {include_blank: 'Select a project' }, {class: 'w-80 mr-8 rounded-md p-2 border border-gray-300 focus:ring-1 focus:ring-seaGreenDark focus:border-seaGreenDark ring-offset-1 ring-offset-white', id: 'project-selection'} %>   
      </div>    
    </div>
  </div>

  <div id="members-container" class="clear-both pt-10">
    <div id="members-error-container">
      <% @report.errors.full_messages_for(:member_ids).each do |message| %>
        <div class="text-red-600 italic text-xs mt-1">Please select atleast one user</div>
      <% end %>
    </div>
    <div>
      <%= form.label :member_ids, 'Members', class: 'block text-gray-700 font-bold mb-2'%>
    </div>
    <div class="mr-4 font-semibold p-1 w-fit float-left m-1">
      <%= check_box_tag "check_all_members", 0, false, {id: "check-all-members", class: 'text-seaGreenDark focus:ring-seaGreenDark focus:ring-offset-2 focus:ring-opacity-50' }%>
      <%= 'Check all'%>
    </div>
    <!--div gets dynamically re-filled with checkboxes on project change -->
    <div id="members-checkboxes">
      <%= render partial: 'checkboxes', locals: {report: @report, text: 'member',checkboxes: @members} %>
    </div>
  </div>

  <div id="tasks-container" class="clear-both pt-10">
    <div id="tasks-error-container">
      <% @report.errors.full_messages_for(:task_ids).each do |message| %>
        <div class="text-red-600 italic text-xs mt-1">Please select atleast one task</div>
      <% end %>
    </div>
    <div>
      <%= form.label :task_ids, 'Tasks', class: 'block text-gray-700 font-bold mb-2'%>
    </div>
    <div class="mr-4 font-semibold p-1 w-fit float-left m-1">
      <%= check_box_tag "check_all_tasks", 0, false, {id: "check-all-tasks", class: 'text-seaGreenDark focus:ring-seaGreenDark focus:ring-offset-2 focus:ring-opacity-50'} %>
      <%= 'Check all'%>
    </div>
    <!--div gets dynamically re-filled with checkboxes on project change -->
    <div id="tasks-checkboxes">
      <%= render partial: 'checkboxes', locals: { report: @report, text: 'task',checkboxes: @tasks } %>
    </div>
  </div>

  <div id="submit-container" class="flex justify-center mt-10">
    <span class="bg-seaGreen w-fit rounded p-3 m-2 hover:bg-seaGreenDark shadow">
      <%= form.submit 'Create report', class: 'rounded bg-seaGreen text-white'  %>
    </span>
  </div>
<% end %>

app/views/project_reports/_projects.html.erb
<option>Select a project</option>
<% projects.each do |project| %>
  <option value="<%= project.id %>"><%= project.name %></option>
<% end %>

app/views/project_reports/_timeframe.html.erb
<div class="flex justify-evenly bg-neutral-50 w-11/12 mt-4 mb-4 p-2 rounded float-right border border-gray-200">
  <div>
    <label for="date_start">Date Start:</label>
    <div class="">
      <%= date_field_tag 'project_report[date_start]', @report.date_start ,class: 'pr-8' %>
    </div>    
  </div>

  <div>
    <label for="date_end">Date End:</label>
    <div class="">
      <%= date_field_tag 'project_report[date_end]', @report.date_end, class: 'pr-8' %>
    </div>  
  </div>
</div>

app/views/project_reports/new.html.erb
<div class="flex flex-col pt-4 mb-40">
  <div class="flex justify-center">
    <div class="max-w-md md:min-w-custom60">
      <div class="flex justify-normal">
        <%= link_to "User report", new_user_report_path, class: 'rounded-t-md bg-tastyWhiteLite border-b hover:border-seaGreen hover:text-seaGreenDarker flex justify-start w-32 flex justify-center pt-2 pb-2' %>
        <%= link_to "Project report", new_project_report_path, class: 'rounded-t-md bg-tastyWhiteLite border-b border-seaGreen flex justify-start w-32 flex justify-center pt-2 pb-2 p-1 text-seaGreenDarker' %>      
      </div>
      <div class=" bg-tastyWhiteLite rounded-r-lg  rounded-b-lg border border-gray-300 p-4" data-controller="project-reports">
        <h1 class="text-2xl m-1 font-bold">Time report</h1>
        <br>
        <%= render 'form' %>
      </div>
    </div>  
  </div>

</div>

app/views/project_reports/show.html.erb
<div class="flex flex-col items-center pt-4 mb-20">
  <div class="max-w-md md:min-w-custom60">
      <div data-controller="report-edit" >
      <div class="flex justify-between ml-4 mb-10">
        <h1 class="font-medium italic text-2xl">Your report</h1>
        <!-- button for viewing the edit form -->
        <button class="pl-3 pr-3 p-2 mr-10 rounded bg-blue-200 hover:bg-blue-300 flex justify-space-x-2" 
                data-action="click->report-edit#editReport">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
            <path stroke-linecap="round" stroke-linejoin="round" d="M10.343 3.94c.09-.542.56-.94 1.11-.94h1.093c.55 0 1.02.398 1.11.94l.149.894c.07.424.384.764.78.93.398.164.855.142 1.205-.108l.737-.527a1.125 1.125 0 011.45.12l.773.774c.39.389.44 1.002.12 1.45l-.527.737c-.25.35-.272.806-.107 1.204.165.397.505.71.93.78l.893.15c.543.09.94.56.94 1.109v1.094c0 .55-.397 1.02-.94 1.11l-.893.149c-.425.07-.765.383-.93.78-.165.398-.143.854.107 1.204l.527.738c.32.447.269 1.06-.12 1.45l-.774.773a1.125 1.125 0 01-1.449.12l-.738-.527c-.35-.25-.806-.272-1.203-.107-.397.165-.71.505-.781.929l-.149.894c-.09.542-.56.94-1.11.94h-1.094c-.55 0-1.019-.398-1.11-.94l-.148-.894c-.071-.424-.384-.764-.781-.93-.398-.164-.854-.142-1.204.108l-.738.527c-.447.32-1.06.269-1.45-.12l-.773-.774a1.125 1.125 0 01-.12-1.45l.527-.737c.25-.35.273-.806.108-1.204-.165-.397-.505-.71-.93-.78l-.894-.15c-.542-.09-.94-.56-.94-1.109v-1.094c0-.55.398-1.02.94-1.11l.894-.149c.424-.07.765-.383.93-.78.165-.398.143-.854-.107-1.204l-.527-.738a1.125 1.125 0 01.12-1.45l.773-.773a1.125 1.125 0 011.45-.12l.737.527c.35.25.807.272 1.204.107.397-.165.71-.505.78-.929l.15-.894z" />
            <path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
          </svg><span class="ml-1">Edit</span>
        </button>
      </div>
      <div class="<%= "hidden" if @show_edit_form == false %>" data-target="report-edit.toggleDiv">
        <%= render partial: 'edit' %>
      </div>    
    </div>

    <div class="flex justify-between mb-3">
      <div class="flex justify-center">
        <!-- form for changing the group_by -->
        <%= form_with url: project_report_update_group_path(@report), method: :patch do |form| %>
          <%= form.label :group_by, 'Group by:', class: 'mr-2' %>
          <%= form.select :group_by, options_for_select(@groupes, @report.group_by),{}, class: 'rounded-md border border-gray-300 pr-8 p-1 mr-1 focus:ring-1 focus:ring-seaGreenDark focus:border-seaGreenDark ring-offset-1 ring-offset-white' %>
          <span class="text-sm rounded bg-seaGreen p-1 hover:bg-seaGreenDark h-full text-white">
            <%= form.submit 'Update', class: ''%>
          </span>
        <% end %>      
      </div>
      <div class="mr-20">
        <!-- form for exporting the report -->
        <%= form_with url: { action: :export, format: :csv }, method: :post do |form| %>
          <%= form.hidden_field :time_regs_hash, value: @time_regs.to_json %>
          <span class="text-sm rounded bg-seaGreen p-2 hover:bg-seaGreenDark h-full text-white">
            <%= form.submit 'Export to CSV', class: '' %>
          </span>
        <% end %>       
      </div>
    </div>
    <div class="bg-slate-50 border-2 border-gray-400">
      <%= render partial: 'reports/report_data', locals: {grouped_report: @grouped_report}   %>
    </div>
  </div>
</div>