config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'time_regs#index'

  resources :project_reports do
    patch :update_group
    collection do
      get 'update_projects_selection'
      get 'update_members_checkboxes'
      get 'update_tasks_checkboxes'
      post 'export'
    end
  end

  resources :user_reports do
    patch :update_group
    collection do
      post 'export'
      get 'update_projects_checkboxes'
      get 'update_tasks_checkboxes'
    end
  end

  resources :clients

  resources :tasks

  match 'projects/import' => 'projects#import', :via => :post
  resources :time_regs do
    patch :toggle_active
    collection do
      get 'export'
      post 'import'
      get 'update_tasks_select'
      get 'new_modal', to: 'time_regs#new', as: :new_modal
    end
  end

  resources :projects do
    resources :memberships
    resources :assigned_tasks
    get 'export', to: 'projects#export', as: 'export_project_time_reg'
  end
end

app/models/project.rb
class Project < ApplicationRecord
  validates :name, presence: true, length: { minimum: 2, maximum: 30 }, uniqueness: true
  validates :description, presence: true, length: { minimum: 2, maximum: 100 }

  belongs_to :client
  has_many :memberships, dependent: :destroy
  has_many :users, through: :memberships
  has_many :time_regs, through: :memberships
  has_many :assigned_tasks, dependent: :destroy
  has_many :tasks, through: :assigned_tasks
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_membership, only: %i[show edit update destroy]

  def index
    @clients = current_user.clients
  end

  # viser et enkelt prosjekt til bruker .where(assigned_tasks: { project_id: @project.id }
  def show
    @project = Project.find(params[:id])
    @tasks = Task.all
    @assigned_tasks = AssignedTask.select('tasks.name, assigned_tasks.id, assigned_tasks.project_id, assigned_tasks.task_id')
                                  .joins(:task)
                                  .where(project_id: @project.id)
  end

  def new
    @clients = Client.all
    @project = Project.new
  end

  def create
    @project = Project.new(project_params.except(:task_ids))

    # adds each task to the project
    project_params[:task_ids].each do |task_id|
      @project.tasks << Task.find(task_id) unless task_id.empty?
    end
    # makes the creater of the project a member
    @project.users << current_user

    # tries to save the project in the db
    if @project.save
      redirect_to @project
    else
      @clients = Client.all
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @is_in_update = true
    @project = Project.find(params[:id])
    @clients = Client.all

    @assigned_tasks = AssignedTask.select('tasks.name, assigned_tasks.id, assigned_tasks.project_id, assigned_tasks.task_id')
                                  .joins(:task)
                                  .where(project_id: @project.id)

    @assigned_task = @project.assigned_tasks.new
    @tasks = Task.all.where.not(id: @project.assigned_tasks.select(:task_id)).select(:id, :name) # no tasks that is already a part om the project
  end

  def update
    @project = Project.find(params[:id])

    if @project.update(project_params)
      flash[:notice] = 'project has been updated'
      redirect_to @project
    else
      @tasks = Task.all
      @clients = Client.all
      @project = Project.find(delete_params[:id])
      @assigned_task = @project.assigned_tasks.new
      @assigned_tasks = AssignedTask.select('tasks.name, assigned_tasks.id, assigned_tasks.project_id, assigned_tasks.task_id')
                                    .joins(:task)
                                    .where(project_id: @project.id)

      flash[:alert] = 'cannot update project'
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @tasks = Task.all
    @clients = Client.all
    @project = Project.find(delete_params[:id])
    @assigned_task = @project.assigned_tasks.new

    # checks the confirmation field before trying to delete
    if delete_params[:confirmation] == 'DELETE'
      if @project.destroy
        flash[:notice] = 'Project deleted'
        redirect_to projects_path
      else
        @assigned_tasks = AssignedTask.select('tasks.name, assigned_tasks.id, assigned_tasks.project_id, assigned_tasks.task_id')
                                      .joins(:task)
                                      .where(project_id: @project.id)

        flash[:alert] = 'Could not delete project'
        render :edit, status: :unprocessable_entity
      end
    else
      @assigned_tasks = AssignedTask.select('tasks.name, assigned_tasks.id, assigned_tasks.project_id, assigned_tasks.task_id')
                                    .joins(:task)
                                    .where(project_id: @project.id)
      flash[:alert] = 'Invalid confirmation'
      render :edit, status: :unprocessable_entity
    end
  end

  def import
    # valid_entries tracks how many entries were successfully imported. imported_time_regs is an empty array for all the time regs.
    imported_time_regs = []
    valid_entries = 0

    # if file is empty or missing
    if params[:file].blank?
      flash[:alert] = "Please select a file to import."
      redirect_to projects_path and return
    end

    file = params[:file].read
    begin
      CSV.parse(file, headers: true) do |row|
        time_reg_params = row.to_hash.slice('date', 'client', 'project', 'task', 'notes', 'minutes', 'first name', 'last name', 'email')
  
        # "Renames" date column to date_worked, which is the name used in the database.
        time_reg_params['date_worked'] = row['date']
        time_reg_params.delete('date')

        # Deletes redundant 'client' column and checks if the client exists
        client = row['client']
        check_client client
        time_reg_params.delete('client')

        # Deletes redundant 'project' column and checks if the project exists
        project = row['project']
        check_project project
        time_reg_params.delete('project')

        # Deletes redundant 'task' column and checks if the task exists
        task = row['task']
        check_task task 
        time_reg_params.delete('task')

        # Deletes redundant 'assigned_task' column and checks if the task exists
        check_assigned_task task_id: @task.id
        time_reg_params['assigned_task_id'] = @assigned_task.id
        
        # Deletes redunant name columns
        time_reg_params.delete('first name')
        time_reg_params.delete('last name')

        # Checks if the e-mail and user is valid, and deletes redundant e-mail column
        email = row['email']
        @user = User.find_by(email: email)
        @membership = Membership.find_or_create_by(user_id: @user.id, project_id: @project.id)
        time_reg_params.delete('email')
        time_reg_params['membership_id'] = @membership.id
      
        # Checks if the time entries are valid and adds them to the array if they are
        # Also adds 1 to the valid_entries variable
        imported_time_reg = @project.time_regs.new(time_reg_params)
        imported_time_reg.updated = Time.now
        imported_time_reg.active = false

        if imported_time_reg.valid?
          imported_time_regs << imported_time_reg
          valid_entries = valid_entries + 1
        else
          Rails.logger.debug "Invalid time entry: #{imported_time_reg.errors.full_messages}"
        end
      end

        # If any valid time entries have been added, import them
      if imported_time_regs.present?
        TimeReg.import(imported_time_regs)
        flash[:notice] = "#{valid_entries} time entries imported successfully."
      else
        flash[:alert] = "No valid time entries found in the file."
      end
    rescue StandardError => e # If the e-mail is invalid, flash and error and redirect
        flash[:alert] = "Invalid e-mail. Please double check the e-mail column for every row."
    end
    redirect_to projects_path
  end

  private

  def project_params
    if action_name == 'create'
      params.require(:project).permit(:client_id, :name, :description, task_ids: [])
    else
      params.require(:project).permit(:client_id, :name, :description)
    end
  end

  def delete_params
    params.permit(:confirmation, :id)
  end

  # ensures that only members have access
  def ensure_membership
    project = Project.find(params[:id])

    return if project.memberships.exists?(user_id: current_user)

    flash[:alert] = 'Access denied'
    redirect_to root_path
  end

  # Checks to see if the client already exists, and creates it if it doesn't
  def check_client(client)
    if !Client.exists?(name: client)
      client_params = { 'name' => client, 'description' => 'Description.' }
      @client = Client.new(client_params)
      @client.save
    else
      @client = Client.find_by(name: client)
    end
  end

  # Checks to see if the project already exists, and creates it if it doesn't
  def check_project(project)
    if !@client.projects.exists?(name: project)
      project_params = { 'client_id' => @client.id, 'name' => project, 'description' => 'Description.' }
      @project = @client.projects.new(project_params)
      @project.save
    else
      @project = @client.projects.find_by(name: project)
    end
  end

  # Checks to see if the task already exists, and creates it if it doesn't
  def check_task(task)
    if !Task.exists?(name: task)
      @task = Task.new(name: task)
      @task.save
    else
      @task = Task.find_by(name: task)
    end
  end

  # Checks to see if the assigned task already exists, and creates it if it doesn't
  def check_assigned_task(task_id)
    if !@project.assigned_tasks.exists?(task_id)
      @assigned_task = @project.assigned_tasks.build('task_id' => @task.id)
      @assigned_task.save
    else
      @assigned_task = @project.assigned_tasks.find_by(task_id: @task.id)
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  # sums a users minutes on a task in a project
  def grouped_time_regs(assigned_task)
    assigned_task.time_regs
                 .joins(membership: :user)
                 .group('users.email')
                 .pluck('users.email', 'SUM(time_regs.minutes)')
  end

  def user_data(email)
    User.find_by(email:)
  end
end

app/views/projects/_form.html.erb
<%= form_with model: @project do |form| %>
  <div>
  <br>
    <%= form.label :client, class: 'block text-gray-700 font-bold mb-1' %>
    <%= form.collection_select :client_id, @clients, :id, :name, { include_blank: false }, { class: 'w-full rounded-md p-2 border border-gray-300 focus:ring-1 focus:ring-seaGreenDark focus:border-seaGreenDark ring-offset-1 ring-offset-white' }  %>
    <% @project.errors.full_messages_for(:client).each do |message|%>
      <div class="text-red-600 italic text-xs mt-1">
        <%= message %>
      </div>
    <% end %>
  </div> 
  <br>
  <div>
    <%= form.label :name, class: 'block text-gray-700 font-bold mb-1' %>
    <%= form.text_area :name, class: 'w-full rounded-md p-2 border border-gray-300 focus:ring-1 focus:ring-seaGreenDark focus:border-seaGreenDark ring-offset-1 ring-offset-white' %>
    <% @project.errors.full_messages_for(:name).each do |message|%>
      <div class="text-red-600 italic text-xs mt-1">
        <%= message %>
      </div>
    <% end %>
  </div>
  <br>
  <div>
    <%= form.label :description, class: 'block text-gray-700 font-bold mb-1' %>
    <%= form.text_area :description, class: 'w-full rounded-md p-2 border border-gray-300 focus:ring-1 focus:ring-seaGreenDark focus:border-seaGreenDark ring-offset-1 ring-offset-white' %>

    <% @project.errors.full_messages_for(:description).each do |message|%>
    <div class="text-red-600 italic text-xs mt-1">
      <%= message %>
    </div>            
  <% end %>
  </div>
  <br>
<div class="mb-14">
  <% if form.object.new_record? %>
    <%= form.label :task_ids, 'Tasks', class: 'block text-gray-700 font-bold mb-1' %>
    <div class="mt-2 ml-2 grid grid-cols-2 gap-4">
      <%= form.collection_check_boxes :task_ids, Task.all, :id, :name do |task| %>
        <div class="flex items-center space-x-2">
          <%= task.check_box(class: 'text-seaGreenDark focus:ring-seaGreenDark focus:ring-offset-2 focus:ring-opacity-50') %>
          <%= task.label(class: 'text-gray-800') %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>


  <div class="actions text-center p-1 m-1 clear-both">
    <span class="rounded bg-seaGreen p-2 hover:bg-seaGreenDark shadow text-white">
      <%= form.submit class: '' %>
    </span>
  </div>
<% end %>

app/views/projects/_import.html.erb
<div class="mt-5 mb-5 bg-tastyWhiteLite border border-gray-400 rounded p-2">
  <div class="text-center">
    <h4 class="">Provide a CSV file with these columns</h4>
    <br>
    <p class="font-semibold">date;client;project;task;notes;minutes;first name;last name;email</p>
    <br>    
    <div >
      <%= form_with url: projects_import_path do |form| %>
        <span class="rounded bg-seaGreen p-2 hover:bg-seaGreenDark shadow text-white mr-2">
          <%= submit_tag "Import CSV", class: ''%>
        </span>
        <%= form.file_field :file %>
      <% end %>    
    </div>
  </div>
  <br>
</div>  

app/views/projects/_project.html.erb
<div class="border-b text-gray-700 border-gray-300 pb-1 pt-1">
    <%= link_to project.name, project_path(project), class: 'italic text-stone-700' %>
</div>

app/views/projects/_remove.html.erb
<div class="mt-5 mb-5 bg-tastyWhiteLite border border-gray-400 rounded p-2">
  <div class="">
    <h4 class="font-semibold text-center">CAREFUL! this action will:</h4>
    <div class="flex justify-center">
      <ul class="italic">
        <li >- Remove all time entries for every member permanently</li>
        <li>- Remove every member from the project</li>
        <li>- Remove every task from the project</li>
        <li>- Delete the project permanently</li>
      </ul>              
    </div>
  </div>
  <br>
  <%= form_tag(project_path(project), method: :delete) do %>
    <span class="flex justify-center pb-2">Please enter "<span class="font-semibold">DELETE</span>" to confirm</span>
    <div class="flex justify-center">
      <%= text_field_tag :confirmation, nil, class: "form-control" %>
      <%= submit_tag "Delete project", class: "ml-2 bg-red-400 p-2 hover:bg-red-500 rounded" %>
    </div>
  <% end %>
</div>  

app/views/projects/edit.html.erb
 <div class="flex flex-col items-center pt-4 mb-20"> 
  <div class="max-w-md md:min-w-custom35 my-4 " data-controller="collapse-delete"> 
    <div class="mb-6 ">
      <%= link_to 'back to project', @project, class: "text-sm italic text-gray-600" %>
    </div>
    <div class='flex justify-between mb-8'>
      <h1 class="font-medium italic text-2xl ml-4">Edit <%= @project.name %></h1><br>
      <button data-action="click->collapse-delete#deleteDiv" 
        class="rounded bg-tastyWhiteLite border border-gray-400 p-2 hover:bg-red-400" 
        data-task-id="delete-button">Delete project
      </button>
    </div>
    <div class="hidden" data-collapse-delete-target="toggleDiv">
      <%= render "projects/remove", project: @project %>
    </div>
    <%= render "form", project: @project %>


    <div class="pt-10">
      <h1 class="font-medium border-b border-gray-300 text-lg italic pb-2">Project tasks</h1>
      <%= render @assigned_tasks %>
    </div>

    <div>
      <h1 class="font-medium text-lg italic mt-8">Add task</h1>
      <%= render 'assigned_tasks/new' %>
      <p class="text-sm">Need more tasks to the project? Create one <%= link_to 'here', new_task_path, class: 'text-blue-600'%></p>
    </div>

    <div class="pt-10">
      <h1 class="font-medium border-b border-gray-300 text-lg italic pb-2">Project members</h1>
      <div class="bg-tastyWhiteLite">
        <%= render @project.memberships %>
      </div>
    </div>

    <div class="pt-10">
      <h1 class="font-medium text-lg italic pb-2">Add member</h1>
      <%= render "memberships/new" %>
    </div>
    <br>
  </div>
</div>

app/views/projects/index.html.erb
<div class="flex flex-col items-center pt-4 mb-28">
  <div class="max-w-md md:min-w-custom35">
    <div class="p-1 my-2 pt-2" data-controller="collapse-delete">
    <!-- NOT A DELETE BUTTON BUT I USES THE SAME STIMULUS CONTROLLER AS THE DELETE BUTTONS-->
      <div class='flex justify-between mb-8'>
        <h1 class="font-medium italic text-2xl ml-4">Your projects</h1><br>
        <button data-action="click->collapse-delete#deleteDiv" 
          class="rounded bg-seaGreen p-2 hover:bg-seaGreenDark shadow text-white" 
          data-task-id="delete-button">Import
        </button>
      </div>
      <div class="hidden" data-collapse-delete-target="toggleDiv">
        <%= render "projects/import" %>
      </div>
      <% @clients.each do |client| %>
        <div class="mb-6">
          <% @projects = current_user.projects.where(projects: {client_id: client.id}) %>
          <div class="flex justify-between border-b border-gray-300 pb-1">
            <%= link_to client.name, client, class: 'font-semibold text-xl"' %>
          </div>
          <% @projects.each do |project| %>
            <div class="border-b border-gray-300 pb-1 pt-1 ">
              <%= link_to project.name, project, class: 'italic text-stone-700 ml-4' %>
            </div>
          <% end %>       
        </div>
      <% end %>    
    </div>
    <div class="flex justify-evenly">
      <%= link_to "New Project", new_project_path, class: 'rounded bg-seaGreen p-2 hover:bg-seaGreenDark shadow text-white'%>
      <%= link_to "New Client", new_client_path, class: 'rounded bg-seaGreen p-2 hover:bg-seaGreenDark shadow text-white'%>
    </div>
  </div>
</div>

app/views/projects/new.html.erb
<div class="flex flex-col items-center pt-4 mb-20">
  <div class="max-w-md md:min-w-custom35 p-1 my-4">
    <h1 class="font-medium italic text-2xl ml-4 mb-2">New project</h1>
      <%= render "form", project: @project  %>
  </div>      
  <%= link_to 'Cancel', :back, class: "rounded bg-tastyWhiteLite p-2 m-2 hover:bg-red-100 shadow text" %>
</div>

app/views/projects/show.html.erb
<div class="flex flex-col items-center pt-9">
  <div class="max-w-md md:min-w-custom35">    
  <h2 class=" text-gray-700 text-sm italic"><%= @project.client.name %></h2>
    <div class='flex justify-between'>        
      <p class='text-3xl mr-4'> <%= @project.name %></p> 
      <%= link_to edit_project_path(@project), class: "pl-3 pr-3 p-2 mr-10 rounded bg-blue-200 hover:bg-blue-300 flex justify-space-x-2" do %>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
          <path stroke-linecap="round" stroke-linejoin="round" d="M10.343 3.94c.09-.542.56-.94 1.11-.94h1.093c.55 0 1.02.398 1.11.94l.149.894c.07.424.384.764.78.93.398.164.855.142 1.205-.108l.737-.527a1.125 1.125 0 011.45.12l.773.774c.39.389.44 1.002.12 1.45l-.527.737c-.25.35-.272.806-.107 1.204.165.397.505.71.93.78l.893.15c.543.09.94.56.94 1.109v1.094c0 .55-.397 1.02-.94 1.11l-.893.149c-.425.07-.765.383-.93.78-.165.398-.143.854.107 1.204l.527.738c.32.447.269 1.06-.12 1.45l-.774.773a1.125 1.125 0 01-1.449.12l-.738-.527c-.35-.25-.806-.272-1.203-.107-.397.165-.71.505-.781.929l-.149.894c-.09.542-.56.94-1.11.94h-1.094c-.55 0-1.019-.398-1.11-.94l-.148-.894c-.071-.424-.384-.764-.781-.93-.398-.164-.854-.142-1.204.108l-.738.527c-.447.32-1.06.269-1.45-.12l-.773-.774a1.125 1.125 0 01-.12-1.45l.527-.737c.25-.35.273-.806.108-1.204-.165-.397-.505-.71-.93-.78l-.894-.15c-.542-.09-.94-.56-.94-1.109v-1.094c0-.55.398-1.02.94-1.11l.894-.149c.424-.07.765-.383.93-.78.165-.398.143-.854-.107-1.204l-.527-.738a1.125 1.125 0 01.12-1.45l.773-.773a1.125 1.125 0 011.45-.12l.737.527c.35.25.807.272 1.204.107.397-.165.71-.505.78-.929l.15-.894z" />
          <path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
        </svg>
        Edit
      <% end %>
    </div>
    
    <div class="p-1">		
      <h2 class="text-md"> <%= @project.description %></h2>
    </div>	

    <div class="border-gray-300 mb-10 pt-10">
      <h4 class="font-medium text-lg italic pb-2">Project members </h4>
      <h4 class="border-t text-gray-700 border-gray-300"><%= render @project.memberships %></h4>
    </div>

    <div>
      <div class="flex justify-between border-b border-gray-300">
        <h4 class="font-bold">Project tasks</h4>
        <h4 class="font-bold mr-16">Hours</h4>
      </div>
      <div data-controller="collapse-hours">
        <% @assigned_tasks.each do |assigned_task| %>
          <div class="border-b text-gray-700 border-gray-300 pb-1 pt-1">
            <div class="flex justify-between">
              <div class="flex justify-between">
                <button data-action="" 
                        class="collapsible mr-2 rounded bg-seaGreen pr-2 pl-2" 
                        data-task-id="<%= assigned_task.id %>">
                        <span class="text-white">V</span>
                </button>                  
                <h4><%= assigned_task.name %></h4>            
              </div>
              <h4 class="font-medium mr-16"><%= convert_time_int(assigned_task.time_regs.sum(:minutes)) %></h4>
            </div>
          </div>
          <div class="hidden bg-tastyWhiteLite" id="collapsible-<%= assigned_task.id %>">
            <% grouped_time_regs(assigned_task).each do |grouped_user| %>
              <div class="flex justify-between p-1 border-b border-gray-300">
                <% user = user_data(grouped_user[0]) %>
                <h4 class="ml-2"><%= user.name %></h4>
                <h4 class="mr-14 pr-1"><%= convert_time_int(grouped_user[1]) %></h4>              
              </div>
            <% end %>
          </div>
          <% end %>         
        </div>    
    </div>


    <div class="flex justify-center p-10">
      <%= link_to "Export to CSV", export_time_regs_path(project_id: @project.id, format: :csv), 
        class: 'rounded bg-seaGreen p-2 hover:bg-seaGreenDark shadow text-white' 
      %>
    </div>
    <br>
</div>